#!/usr/bin/env node
/**
 * Proves that the ID-card QR code and Code 128 barcode are REAL, scannable
 * symbols — the Item 18 bug was a card whose codes nothing could act on.
 *
 *  1. Code 128 pattern table integrity (107 symbols, widths 11/13, unique).
 *  2. Our Code 128 SVG/modules are decoded by ZXing (independent industry
 *     decoder used by most Android scanner apps) at several print scales,
 *     with blur, noise, uneven lighting and upside-down orientation.
 *  3. Our built-in scan-line decoder (the iPhone/Safari fallback) reads the
 *     same degraded images, reads ZXing-encoded Code 128 (incl. code set C)
 *     and rejects a corrupted checksum.
 *  4. The card QR (verification URL) generated by the vendored
 *     qrcode-generator is decoded by the vendored jsQR AND by ZXing.
 */
import fs from 'node:fs/promises';
import vm from 'node:vm';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ZX = require('@zxing/library');
const root = new URL('../', import.meta.url);
const read = (p) => fs.readFile(new URL(p, root), 'utf8');

let passed = 0, failed = 0;
const ok = (cond, label, extra = '') => {
  if (cond) { passed += 1; console.log(`  PASS  ${label}`); }
  else { failed += 1; console.log(`  FAIL  ${label}${extra ? ' — ' + extra : ''}`); }
};

const sandbox = { console, URL, document: { currentScript: { src: 'https://example.org/app/assets/js/dc-codes.js' }, getElementsByTagName: () => [] }, location: { href: 'https://example.org/app/pages/idcard.html' } };
sandbox.window = sandbox; sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(await read('assets/js/vendor/qrcode-generator.js'), sandbox, { filename: 'qrcode-generator.js' });
vm.runInContext(await read('assets/js/vendor/jsqr.js'), sandbox, { filename: 'jsqr.js' });
vm.runInContext(await read('assets/js/dc-codes.js'), sandbox, { filename: 'dc-codes.js' });
const C = sandbox.DCCodes;
ok(!!C && typeof sandbox.qrcode === 'function' && typeof sandbox.jsQR === 'function', 'vendored libraries and DCCodes load without network');

console.log('Code 128 table');
ok(C._patterns.length === 107, '107 symbol patterns');
ok(C._patterns.slice(0, 106).every((p) => p.length === 6 && [...p].reduce((a, b) => a + +b, 0) === 11), 'symbols 0–105 are 6 elements / 11 modules');
ok(C._patterns[106].length === 7 && [...C._patterns[106]].reduce((a, b) => a + +b, 0) === 13, 'STOP is 7 elements / 13 modules');
ok(new Set(C._patterns).size === 107, 'all patterns are unique');
const vals = C.code128Values('DC-000123');
ok(vals[0] === 104 && vals.at(-1) === 106, 'starts with START-B and ends with STOP');
// Hand-computed: 104 + 48·1 + 42·2 + 42·3 + 17·4 + 18·5 + 19·6 + 35·7 = 879 → 879 mod 103 = 55.
ok(C.code128Values('PJJ123C').at(-2) === 55, 'mod-103 checksum matches a hand-computed Start-B example (PJJ123C → 55)');
ok(C.verifyUrl('abc') === 'https://example.org/app/pages/verify.html?c=abc', 'verification URL honours sub-path deployments');
ok(C.registerUrl('easter-2026', 'WhatsApp!') === 'https://example.org/app/pages/register.html?p=easter-2026&src=whatsapp', 'share link carries a sanitised ?src= channel tag');

// ---- raster helpers --------------------------------------------------------
function rasterBars(bits, { scale = 3, height = 60, blur = 0, noise = 0, gradient = 0, flip = false, pad = 20 } = {}) {
  const w = bits.length * scale + pad * 2, h = height + pad * 2;
  const lum = new Float64Array(w * h).fill(255);
  for (let y = pad; y < pad + height; y += 1)
    for (let x = 0; x < bits.length * scale; x += 1)
      if (bits[Math.floor(x / scale)] === '1') lum[y * w + pad + x] = 20;
  return finish(lum, w, h, { blur, noise, gradient, flip });
}
function rasterMatrix(matrix, { scale = 4, quiet = 4, blur = 0, noise = 0 } = {}) {
  const n = matrix.length, w = (n + quiet * 2) * scale;
  const lum = new Float64Array(w * w).fill(255);
  for (let y = 0; y < w; y += 1) for (let x = 0; x < w; x += 1) {
    const r = Math.floor(y / scale) - quiet, c = Math.floor(x / scale) - quiet;
    if (r >= 0 && c >= 0 && r < n && c < n && matrix[r][c]) lum[y * w + x] = 15;
  }
  return finish(lum, w, w, { blur, noise });
}
let seed = 7;
const rand = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
function finish(lum, w, h, { blur, noise, gradient = 0, flip = false }) {
  let src = lum;
  for (let pass = 0; pass < blur; pass += 1) {
    const out = new Float64Array(src.length);
    for (let y = 0; y < h; y += 1) for (let x = 0; x < w; x += 1) {
      let s = 0, c = 0;
      for (let dx = -1; dx <= 1; dx += 1) { const xx = x + dx; if (xx >= 0 && xx < w) { s += src[y * w + xx]; c += 1; } }
      out[y * w + x] = s / c;
    }
    src = out;
  }
  const rgba = new Uint8ClampedArray(w * h * 4);
  for (let y = 0; y < h; y += 1) for (let x = 0; x < w; x += 1) {
    const sx = flip ? w - 1 - x : x;
    let v = src[y * w + sx] - gradient * (x / w) + (rand() - 0.5) * 2 * noise;
    v = Math.max(0, Math.min(255, v));
    const o = (y * w + x) * 4; rgba[o] = rgba[o + 1] = rgba[o + 2] = v; rgba[o + 3] = 255;
  }
  return { data: rgba, width: w, height: h };
}
function zxingDecode(img, format) {
  const lumBytes = new Uint8ClampedArray(img.width * img.height);
  for (let i = 0; i < lumBytes.length; i += 1) lumBytes[i] = img.data[i * 4];
  const source = new ZX.RGBLuminanceSource(lumBytes, img.width, img.height);
  const bitmap = new ZX.BinaryBitmap(new ZX.HybridBinarizer(source));
  const hints = new Map([[ZX.DecodeHintType.POSSIBLE_FORMATS, [format]], [ZX.DecodeHintType.TRY_HARDER, true]]);
  const reader = new ZX.MultiFormatReader(); reader.setHints(hints);
  try { const res = reader.decode(bitmap); return { text: res.getText(), format: res.getBarcodeFormat() }; }
  catch { return null; }
}

console.log('Code 128 scanning (ZXing + built-in decoder)');
const samples = ['DC-000001', 'DC-000123', 'LAG-104857', 'MEM-9', 'A1B2-C3D4'];
const conditions = [
  ['clean print, 3px/module', {}],
  ['small print, 2px/module', { scale: 2 }],
  ['blurred camera frame', { blur: 2, scale: 3 }],
  ['sensor noise ±35', { noise: 35 }],
  ['uneven lighting (gradient 90)', { gradient: 90 }],
  ['card held upside-down', { flip: true }],
];
for (const text of samples) {
  const bits = C.code128Modules(text);
  for (const [label, opt] of conditions) {
    const img = rasterBars(bits, opt);
    const zx = zxingDecode(img, ZX.BarcodeFormat.CODE_128);
    const own = C.decodeCode128Image(img);
    ok(zx && zx.text === text && own === text, `${text}: ${label}`, `zxing=${zx && zx.text} own=${own}`);
  }
}
const svg = C.code128Svg('DC-000123');
ok(/^<svg[^>]+viewBox/.test(svg) && svg.includes('DC-000123') && !/<script/i.test(svg), 'barcode SVG is well-formed, labelled and script-free');
ok(C.code128Svg('<x>').includes('&lt;x&gt;'), 'barcode label is XML-escaped');
let threw = false; try { C.code128Values('naïve'); } catch { threw = true; }
ok(threw, 'non-ASCII input is refused instead of producing an unreadable code');

// Code 128 printed by OTHER systems often uses code set C for digit runs
// (e.g. membership numbers from label printers). Build such symbols by hand
// from the standard table, confirm ZXing reads them, then confirm our decoder.
function modulesFromValues(values) {
  let sum = values[0]; for (let i = 1; i < values.length; i += 1) sum += values[i] * i;
  const all = [...values, sum % 103, 106];
  let bits = '0'.repeat(10);
  for (const v of all) [...C._patterns[v]].forEach((w, i) => { bits += (i % 2 ? '0' : '1').repeat(+w); });
  return bits + '0'.repeat(10);
}
for (const [text, values] of [
  ['12345678', [105, 12, 34, 56, 78]],
  ['DC-000123', [104, 36, 35, 13, 99, 0, 1, 23]],
  ['0099-AB', [105, 0, 99, 100, 13, 33, 34]],
]) {
  const img = rasterBars(modulesFromValues(values), { scale: 3 });
  const zx = zxingDecode(img, ZX.BarcodeFormat.CODE_128);
  ok(zx && zx.text === text && C.decodeCode128Image(img) === text, `code-set-C symbol "${text}" decoded identically by ZXing and built-in decoder`, `zx=${zx && zx.text} own=${C.decodeCode128Image(img)}`);
}
// Corrupt one symbol → checksum must reject.
const good = C.code128Modules('DC-000123');
const corrupt = good.slice(0, 40) + (good[40] === '1' ? '0' : '1') + good.slice(41);
const bad = C.decodeCode128Image(rasterBars(corrupt, { scale: 3 }));
ok(bad === null || bad === 'DC-000123', 'a damaged barcode never decodes to a different member number');

console.log('QR code');
const token = 'a3f1c2d4e5b60718293a4b5c6d7e8f90';
const url = C.verifyUrl(token);
const matrix = C.qrMatrix(url, 'M');
ok(matrix.length >= 25, `QR generated (${matrix.length}×${matrix.length} modules)`);
for (const [label, opt] of [['clean', {}], ['small print 3px', { scale: 3 }], ['blur + noise', { blur: 1, noise: 30 }]]) {
  const img = rasterMatrix(matrix, opt);
  const js = sandbox.jsQR(img.data, img.width, img.height);
  const zx = zxingDecode(img, ZX.BarcodeFormat.QR_CODE);
  ok(js && js.data === url && zx && zx.text === url, `QR ${label}: jsQR and ZXing both decode the verification URL`, `jsqr=${js && js.data} zx=${zx && zx.text}`);
}
const qsvg = C.qrSvg(url, { size: 120 });
const vb = +qsvg.match(/viewBox="0 0 (\d+)/)[1];
ok(vb === matrix.length + 8, 'QR SVG includes the 4-module quiet zone on every side');
ok(C.qrSvg('x', { dark: 'red;background:url(x)' }).includes('#0f172a'), 'unsafe colours are rejected');

console.log('Pages use the vendored, pinned libraries');
const idcard = await read('pages/idcard.html');
const attendance = await read('pages/attendance.html');
ok(!/qrcodejs|cdnjs[^"]*qrcode/i.test(idcard), 'idcard.html no longer loads qrcodejs from a CDN');
ok((idcard.match(/vendor\/qrcode-generator\.js/g) || []).length === 1 && idcard.includes('dc-codes.js'), 'idcard.html loads qrcode-generator exactly once + dc-codes.js');
ok(!/unpkg\.com\/html5-qrcode/i.test(attendance), 'attendance.html no longer loads an unpinned scanner from unpkg');
ok(attendance.includes('dc-codes.js') && attendance.includes("sb.rpc('dc_scan_attendance'") && attendance.includes('wireWedge'), 'attendance scanner resolves codes server-side through dc_scan_attendance (camera + USB wedge)');
ok(attendance.includes('data-mid="${m.id}"') && !attendance.includes('att-${member.id}'), 'scan result updates the row the page actually renders (data-mid)');
ok(/Auth\.canManage\(me\)[\s\S]{0,200}qr-scan-btn/.test(attendance), 'unit leaders as well as administrators get the scanning desk');

console.log('Offline styling + service-worker precache');
const offlineCss = await read('assets/css/tailwind-offline.css');
const boot = await read('assets/js/boot.js');
const sw = await read('sw.js');
ok(offlineCss.length > 5000 && /\.h-14\{/.test(offlineCss) && /\.md\\:grid-cols-2\{/.test(offlineCss), 'tailwind-offline.css is built and covers page utilities');
for (const cls of ['inset-\\[18\\%\\]', 'max-w-\\[130px\\]', 'rounded-3xl', 'bg-emerald-600', 'bg-red-600']) {
  ok(offlineCss.includes('.' + cls + '{') || offlineCss.includes('.' + cls + ','), 'offline CSS includes .' + cls.replace(/\\/g, ''));
}
ok(boot.includes('tailwind-offline.css') && /if \(!tailwindLoaded\(\)\) linkOfflineCss\(\);/.test(boot), 'boot.js links the offline sheet immediately when the CDN failed');
for (const asset of ['tailwind-offline.css', 'dc-codes.js', 'vendor/qrcode-generator.js', 'vendor/jsqr.js', 'pages/verify.html', 'pages/idcard.html']) {
  ok(sw.includes(asset), 'service worker precaches ' + asset);
}

console.log(`\ncodes suite: ${passed} passed, ${failed} failed`);
if (failed) process.exit(1);
